asservizi/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from contact_form import views, forms
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'asservizi.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('sito.urls')),
    url(r'^contact/', include("contact_form.urls", namespace="contact_form")),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:  
        urlpatterns += patterns('',  
                                #REMOVE IT in production phase  
                                (r'^sito/media/(?P<path>.*)$', 'django.views.static.serve',  
                                {'document_root': settings.MEDIA_ROOT})
          )  

contact_form/urls.py
from django.conf.urls import url, patterns

from contact_form import views, forms


urlpatterns = patterns('',
    url(r'^$', views.ContactFormView.as_view(
        template_name="contact_form/contact.html",
        form_class=forms.BasicContactForm,
    ), name="contact"),
    url(r'^completed/$', views.CompletedPage.as_view(), name="completed"),
)

sito/urls.py
# Create your views here.
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.views.generic import TemplateView
from django.views.generic import ListView, DetailView
#from django.views.generic import object_detail
#from django.views.generic import ListView
from sito import views
from contact_form import views, forms
from sito.views import HomeView, PageView, AmbienteView, FormazioneView, OrganizazzioneView, PraticheView, PerizieView, SicurezzaView, ProblematicaView, RichiestaView, SitoFeed
from sito.models import Page

from django.shortcuts import render, render_to_response, get_object_or_404

from views import search
#from django.contrib.syndication.views import Feed


urlpatterns = patterns('',
   url(r'^$', HomeView.as_view()),
   url(r'^ambiente$', AmbienteView.as_view()),
   url(r'^sicurezza$', SicurezzaView.as_view()),
   url(r'^formazione$', FormazioneView.as_view()),
   url(r'^organizazzione$', OrganizazzioneView.as_view()),
   url(r'^pratiche$', PraticheView.as_view()),
   url(r'^perizie$', PerizieView.as_view()),
   url(r'^pagina/(?P<pk>\d+)/$', PageView.as_view()),
   url(r'^contact/', include('contact_form.urls')),
   url(r'^problematica$', ProblematicaView.as_view()),
   url(r'^richiesta$', RichiestaView.as_view()),
   url(r'^results/$', 'sito.views.search'),
   url(r'^feed/$', SitoFeed()),
   #url(r'^([-_A-Za-z0-9]+)/$', views.dettaglio),
   #url(r'^pagine/(?P<pk>\d+)/$', PageView.as_view()),
  )

sito/models.py
from django.db import models
from tinymce import models as tinymce_models
from image_cropping import ImageRatioField, ImageCropField
from django import forms
from django.forms import widgets
from django.forms import ModelForm, Textarea


# Create your models here.

class Image(models.Model):
    image_field = models.ImageField(upload_to='uploaded_images')

class Documento(models.Model):
    documento = models.FileField(upload_to='uploaded_documenti')

class Categoria(models.Model):
    categoria = models.CharField(max_length=200, blank=True, null=True)
    
    def __unicode__ (self):
        return self.categoria

class Page(models.Model):
    titolo = models.CharField(max_length=200)
    categoria = models.ForeignKey(Categoria, blank=True, null=True)
    intro = models.TextField(blank=True, null=True)
    #body = tinymce_models.HTMLField()
    body = tinymce_models.HTMLField(blank=True, null=True)
    image = models.ImageField(blank=True, null=True, upload_to='uploaded_images')
    cropping = ImageRatioField('image', '500x136')
    pub_date = models.DateTimeField('date published')

    def __unicode__ (self):
        return self.titolo

class Allegati(models.Model):
    titoloallegato = models.CharField(max_length=200)
    descrizione = models.TextField(blank=True, null=True)
    sezione = models.ForeignKey(Page)
    allegato = models.ForeignKey(Documento)
    pub_date = models.DateTimeField('date published')

    def __unicode__ (self):
        return self.titoloallegato

class Galleria(models.Model):
    gallerianome = models.CharField(max_length=200)
    pagina = models.ForeignKey(Page)
    image = models.ForeignKey(Image)
    cropping = ImageRatioField('image__image_field', '660x300')
    croppingthumb = ImageRatioField('image__image_field', '350x213')
    
    def __unicode__ (self):
        return unicode(self.gallerianome) 

'''# CONTACT

class ContactForm(forms.Form):
    subject = forms.CharField(widget=forms.TextInput(attrs={'class':'contactform'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class':'contactform'}))
    city = subject = forms.CharField(widget=forms.TextInput(attrs={'class':'contactform'}))
    tel = subject = forms.CharField()
    fax = subject = forms.CharField(widget=forms.TextInput(attrs={'class':'contactform'}))
    mail = subject = forms.CharField(widget=forms.TextInput(attrs={'class':'contactform'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class':'contactform'}))
    sender = forms.CharField(widget=forms.TextInput(attrs={'class':'contactform'}))
    cc_myself = forms.BooleanField(required=False) 


'''

sito/views.py
# Create your views here.
from django.views.generic import ListView, DetailView
from django.views.generic import TemplateView
from django.core.paginator import Paginator, InvalidPage, EmptyPage
from django.core.urlresolvers import reverse
from django.template import Context
from django.shortcuts import render
from django.shortcuts import render, render_to_response, get_object_or_404
from django.template import RequestContext
from models import Page, Categoria, Galleria, Allegati, Documento, Image
from django.http import HttpResponseRedirect

from contact_form import views, forms
from contact_form.forms import *
from contact_form.views import *

from django.db.models import Q

from django.contrib.syndication.views import Feed



class HomeView(ListView):
    queryset = Page.objects.all()
    queryset = Page.objects.filter(categoria_id=1)
    template_name = 'sicurezza.html'

class SicurezzaView(ListView):
    queryset = Page.objects.filter(categoria_id=1)
    context_object_name = 'page_list'
    template_name = 'sicurezza.html'

class AmbienteView(ListView):
    queryset = Page.objects.filter(categoria_id=2)
    context_object_name = 'page_list'
    template_name = 'ambiente.html'

class FormazioneView(ListView):
    queryset = Page.objects.filter(categoria_id=3)
    context_object_name = 'page_list'
    template_name = 'formazione.html'

class OrganizazzioneView(ListView):
    queryset = Page.objects.filter(categoria_id=4)
    context_object_name = 'page_list'
    template_name = 'organizazzione.html'

class PraticheView(ListView):
    queryset = Page.objects.filter(categoria_id=5)
    context_object_name = 'page_list'
    template_name = 'pratiche.html'

class PerizieView(ListView):
    queryset = Page.objects.filter(categoria_id=6)
    context_object_name = 'page_list'
    template_name = 'perizie.html'

class PageView(DetailView):
    queryset = Page.objects.all()
    context_object_name = 'page'
    template_name = 'pagina.html'

    def get_context_data(self, **kwargs):
    # Call the base implementation first to get a context
        context = super(PageView, self).get_context_data(**kwargs)
        ciao = Page.objects.all()
        context['allegati_list'] = Allegati.objects.filter(allegato=context['page'].id)
        context['galleria_list'] = Galleria.objects.filter(pagina=context['page'].id)
        context['form2'] = BasicContactForm
        return context

class ProblematicaView(ListView):
    queryset = Page.objects.all()
    context_object_name = 'page_list'
    template_name = 'problematica.html'

    def get_context_data(self, **kwargs):
    # Call the base implementation first to get a context
        context = super(ListView, self).get_context_data(**kwargs)
        #ciao = Page.objects.all()
        #context['allegati_list'] = Allegati.objects.filter(allegato=context['page'].id)
        #context['galleria_list'] = Galleria.objects.filter(pagina=context['page'].id)
        context['form2'] = BasicContactForm
        return context

class RichiestaView(ListView):
    queryset = Page.objects.all()
    context_object_name = 'page_list'
    template_name = 'richiesta.html'

    def get_context_data(self, **kwargs):
    # Call the base implementation first to get a context
        context = super(ListView, self).get_context_data(**kwargs)
        #ciao = Page.objects.all()
        #context['allegati_list'] = Allegati.objects.filter(allegato=context['page'].id)
        #context['galleria_list'] = Galleria.objects.filter(pagina=context['page'].id)
        context['form2'] = BasicContactForm
        return context

# CONTATTI
'''
from django.shortcuts import render
from django.http import HttpResponseRedirect

def contact(request):
    if request.method == 'POST': # If the form has been submitted...
        form = ContactForm(request.POST) # A form bound to the POST data
        if form.is_valid():
            subject = form.cleaned_data['subject']
            address = form.cleaned_data['address']
            city = form.cleaned_data['city']
            tel = form.cleaned_data['tel']
            fax = form.cleaned_data['fax']
            mail = form.cleaned_data['mail']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['pierangelo1982@gmail.com']
            if cc_myself:
                recipients.append(sender)

        from django.core.mail import send_mail
        send_mail(subject, address, city, tel, fax, mail, message, sender, recipients)
        return HttpResponseRedirect('/thanks/') # Redirect after POST
    else:
        form = ContactForm() # An unbound form

    return render(request, 'contact.html', {
        'form': form,
    })


'''

def search(request):

    try:
        q = request.GET['q']
        page_list = Page.objects.filter(titolo__search=q) | \
                Page.objects.filter(intro__search=q) | \
                Page.objects.filter(body__search=q)
        return render_to_response('results.html', {'page_list':page_list, 'q':q}, context_instance=RequestContext(request))
    except KeyError:
        return render_to_response('results.html', context_instance=RequestContext(request))


#### PROVA FEED RSS


class SitoFeed(Feed):
    title = "AS servizi alle imprese s.r.l"
    description = "Benvenuto nel sito di AS servizi alle imprese s.r.l."
    link = "/feed/"

    def items(self):
        return Page.objects.all().order_by("-pub_date")[:5]
    def item_title(self, item):
        return item.titolo
    def item_description(self, item):
        return item.body
    def item_link(self, item):
        return u"/pagina/%d" % item.id 

sito/templates/ambiente.html
{% extends "base2.html" %}




{% block content %}

<script>
$(function(){
    $('a#linkprova').on('click', function(e){
        e.preventDefault();
        var page_url=$(this).prop('href');
        $('#testosottocard').load(page_url);
    });
});
</script>

{% for page in page_list %}

<div class="areaintro">
<h3>{{ page.titolo }}</h3>
<p>{{page.intro|safe|truncatechars:340}}</p>
<a id="linkprova" href="{{MYPATH}}/pagina/{{ page.id }}">continua...</a></p>
<p></br></p>
<hr>
</div>
{% endfor %}

{% endblock content %}

sito/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=1100" />
<script src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
<title>AS servizi alle imprese</title>
<link href="{{ STATIC_URL }}/stiloso.css" rel="stylesheet" type="text/css" />
<link href="{{ STATIC_URL }}/menu1.css" rel="stylesheet" type="text/css" />



<!-- SHARE THIS -->

<script type="text/javascript">var switchTo5x=false;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "8268944a-900a-49af-a556-4374bbb32b03", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

<!-- FINE SHARE -->
</head>


<!-------- FINE ------------------>

<script type="text/javascript">
$(document).ready(function() {
  $('ul#menux li a[href^="/' + location.pathname.split("/")[1] + '"]').addClass('active');
});
</script>

<!--------------- MENU ACTIVE ----------->
<script>
$(document).ready(function(){
    var $menu = $("ul#menux li a");                
    $menu.click(function(){
        $menu.each(function(){
            $(this).removeClass("active");
        });
        $(this).addClass("active");                  
    });
 });
</script>


<!----- cssmenu script 
<script>
$(document).ready(function(){
    var $cssmenu = $("#cssmenu li a");                
    $cssmenu.click(function(){
        $cssmenu.each(function(){
            $(this).removeClass("active");
        });
        $(this).addClass("active");                  
    });
 });
</script> ----->

<!----------- HEADER --------->

<!----------------- HOVER ------------------------->
<script> 

$(document).ready(function(){ 

    $("li.menux1").on('mouseover', function(){ $
		("#header").removeClass().addClass("header1");
	});
	$("li.menux2").on('mouseover', function(){ $
		("#header").removeClass().addClass("header2");
	});
	$("li.menux3").on('mouseover', function(){ $
		("#header").removeClass().addClass("header3");
	});	
	$("li.menux4").on('mouseover', function(){ $
		("#header").removeClass().addClass("header4");
	}); 	
	$("li.menux5").on('mouseover', function(){ $
		("#header").removeClass().addClass("header5");
	});
	$("li.menux6").on('mouseover', function(){ $
		("#header").removeClass().addClass("header6");
	});
});


</script>

<!----------- CLICK HEADER --------->
<script> 

$(document).ready(function(){ 

    $("li.menux1").click( function(){ $
		("#header").removeClass().addClass("header1");
	});
	$("li.menux2").click( function(){ $
		("#header").removeClass().addClass("header2");
	});
	$("li.menux3").click( function(){ $
		("#header").removeClass().addClass("header3");
	}); 	
	$("li.menux4").click( function(){ $
		("#header").removeClass().addClass("header4");
	}); 	
	$("li.menux5").click( function(){ $
		("#header").removeClass().addClass("header5");
	});
	$("li.menux6").click( function(){ $
		("#header").removeClass().addClass("header6");
	});
});


</script>

<!--fine header -->


<body topmargin="0" id="body">
<!-- Header -->
<div id="sfondo"></div>
<div id="header" class="header">

<!-- TOP MENU -->
<div id="topmenu">
<div id="drop-menutop"><ul id="menutop">
	<li class="menutop"><a href="{{ MYPATH }}/">Home</a></li>
				<li class="menutop"><a href="#">Mission</a>
				<li class="menutop"><a href="#">Corporate</a></li>
				<li><a href="{{ MYPATH }}/contact">Contatti</a></li>
                </ul>
</div>
</div>


<!------------ --->
<div id="logo"></div>
</div>

<!-- Menu guida -->
<div id="contmenu">
<div id="drop-menux"><ul id="menux">
				<li class="menux1"><a href="{{ MYPATH }}/sicurezza">Sicurezza</br>e Salute</a></li>
				<li class="menux2"><a href="{{ MYPATH }}/ambiente">Ambiente</br>e Territorio</a>
				<li class="menux3"><a href="{{ MYPATH }}/formazione">Formazione</br>Aziendale</a></li>
				<li class="menux4"><a href="{{ MYPATH }}/organizazzione">Organizazzione e</br>Gestione Aziendale</a></li>
                <li class="menux5"><a href="{{ MYPATH }}/pratiche">Pratiche</br>Amministrative</a></li>
                <li class="menux6"><a href="{{ MYPATH }}/perizie">Perizie</br>Tecnice e CTP</a></li>
			</ul>
		</div>      
        
</div>


<!-- CARICAMENTO DJANGO -->

<div id="contenitore">

<div id="leftside">
<!---- MENU SINISTRA -->
<!---- MENUUUUUUUU SINISTRAAAAA -------->
<script>
$(function(){
    $('#cssmenu li a').on('click', function(e){
        e.preventDefault();
        var page_url=$(this).prop('href');
        $('#testosottocard').load(page_url);
    });
});
</script>

<script>
$(document).ready(function(){
    var $cssmenu = $("#cssmenu li a");                
    $cssmenu.click(function(){
        $cssmenu.each(function(){
            $(this).removeClass("activecss");
        });
        $(this).addClass("activecss");                  
    });
 });
</script>

{% include "componenti/menusicurezza.html" %}
</div>
<!-- FINE MENU SINISTRA -->

<div id="content">
<div id="cercatore">
<div class="cercami"><form action="{{ MYPATH }}/results/" action="" method="get">Cerca: <input id="id_q" name="q" type="text" name="textfield" style="width: 400px; height: 20px;"></form>{% csrf_token %}</div>
</div>

<div id="testosottocard">

{% block content %}

{% endblock %} 
<p></p>

</div>
</div>
<div id="rightside">
	<p></p>
{% include "componenti/login.html" %}
{% include "componenti/newsletter.html" %}
{% include "componenti/social.html" %}
<p>&nbsp;</p>
<p><a class="problem" href="{{ MYPATH }}/problematica">PARLACI</br>DELLA TUA</br>PROBLEMATICA</a></p>
<p></br></p>
<p><a class="richiest" href="{{ MYPATH }}/richiesta">RICHIESTA</br>INFORMAZIONI</a></p>
<!--
<p><img src="{{ STATIC_URL }}/img/rx.jpg" class="imgrx"></p>
-->
</div>


<div id="footero">
<div id="footeroleft"></div>
<div id="footerocenter"><img src="{{ STATIC_URL }}/img/loghifootera.jpg"></div>
</div>

<div id="footer">
<div id="footerleft"></div>
<div id="footercenter"></br>AS Servizi alle imprese s.r.l. -  C.F. e P.I: 02288730167  -  Via C. Maffei, 11 -  24128 BERGAMO  -  Tel. 035.238112 - Fax 035.224525 - <a href="mailto:info@asservizi.it">info@asservizi.it</a></div>
<div id="footerright">   </br>Designed by</br>grafica<B>PASSWORD</B></div>
</div>
</div>
</div>
</body>
</html>

sito/templates/base5.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=1100" />
<script src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
<title>AS servizi alle imprese</title>
<link href="{{ STATIC_URL }}/stiloso.css" rel="stylesheet" type="text/css" />
<link href="{{ STATIC_URL }}/menu5.css" rel="stylesheet" type="text/css" />

<!-- SHARE THIS -->

<script type="text/javascript">var switchTo5x=false;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "8268944a-900a-49af-a556-4374bbb32b03", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>

<!-- FINE SHARE -->

</head>

<!------------ MENU CARICA LEFT ------------>


<!--------------- MENU ACTIVE ----------->
<script>
$(document).ready(function(){
    var $menu = $("ul#menux li a");                
    $menu.click(function(){
        $menu.each(function(){
            $(this).removeClass("active");
        });
        $(this).addClass("active");                  
    });
 });
</script>


<!----- cssmenu script 
<script>
$(document).ready(function(){
    var $cssmenu = $("#cssmenu li a");                
    $cssmenu.click(function(){
        $cssmenu.each(function(){
            $(this).removeClass("active");
        });
        $(this).addClass("active");                  
    });
 });
</script>
----->
<!----------- HEADER --------->

<!----------------- HOVER ------------------------->
<script> 

$(document).ready(function(){ 

    $("li.menux1").on('mouseover', function(){ $
		("#header").removeClass().addClass("header1");
	});
	$("li.menux2").on('mouseover', function(){ $
		("#header").removeClass().addClass("header2");
	});
	$("li.menux3").on('mouseover', function(){ $
		("#header").removeClass().addClass("header3");
	});	
	$("li.menux4").on('mouseover', function(){ $
		("#header").removeClass().addClass("header4");
	}); 	
	$("li.menux5").on('mouseover', function(){ $
		("#header").removeClass().addClass("header5");
	});
	$("li.menux6").on('mouseover', function(){ $
		("#header").removeClass().addClass("header6");
	});
});


</script>

<!----------- CLICK HEADER --------->
<script> 

$(document).ready(function(){ 

    $("li.menux1").click( function(){ $
		("#header").removeClass().addClass("header1");
	});
	$("li.menux2").click( function(){ $
		("#header").removeClass().addClass("header2");
	});
	$("li.menux3").click( function(){ $
		("#header").removeClass().addClass("header3");
	}); 	
	$("li.menux4").click( function(){ $
		("#header").removeClass().addClass("header4");
	}); 	
	$("li.menux5").click( function(){ $
		("#header").removeClass().addClass("header5");
	});
	$("li.menux6").click( function(){ $
		("#header").removeClass().addClass("header6");
	});
});


</script>

<!----------- fine header ------->


<body topmargin="0" id="body">
<!-- Header -->
<div id="sfondo"></div>
<div id="header" class="header">

<!-- TOP MENU -->
<div id="topmenu">
<div id="drop-menutop"><ul id="menutop">
	<li class="menutop"><a href="{{ MYPATH }}/">Home</a></li>
				<li class="menutop"><a href="#">Mission</a>
				<li class="menutop"><a href="#">Corporate</a></li>
				<li><a href="{{ MYPATH }}/contact">Contatti</a></li>
                </ul>
</div>
</div>


<!------------ --->
<div id="logo"></div>
</div>

<!-- Menu guida -->
<div id="contmenu">
<div id="drop-menux"><ul id="menux">
				<li class="menux1"><a href="{{ MYPATH }}/sicurezza">Sicurezza</br>e Salute</a></li>
				<li class="menux2"><a href="{{ MYPATH }}/ambiente">Ambiente</br>e Territorio</a>
				<li class="menux3"><a href="{{ MYPATH }}/formazione">Formazione</br>Aziendale</a></li>
				<li class="menux4"><a href="{{ MYPATH }}/organizazzione">Organizazzione e</br>Gestione Aziendale</a></li>
                <li class="menux5"><a href="{{ MYPATH }}/pratiche">Pratiche</br>Amministrative</a></li>
                <li class="menux6"><a href="{{ MYPATH }}/perizie">Perizie</br>Tecnice e CTP</a></li>
			</ul>
		</div>      
        
</div>


<! --------- CARICAMENTO DJANGO ----------------->

<div id="contenitore">

<div id="leftside">
<script>
$(function(){
    $('#cssmenu li a').on('click', function(e){
        e.preventDefault();
        var page_url=$(this).prop('href');
        $('#testosottocard').load(page_url);
    });
});
</script>



<script>
$(document).ready(function(){
    var $cssmenu = $("#cssmenu li a");                
    $cssmenu.click(function(){
        $cssmenu.each(function(){
            $(this).removeClass("activecss");
        });
        $(this).addClass("activecss");                  
    });
 });
</script>


<!---- MENU SINISTRA -->

{% include "componenti/menupratiche.html" %}
</div>
<!-- FINE MENU SINISTRA -->

<div id="content">
<div id="cercatore">
<div class="cercami"><form action="{{ MYPATH }}/results/" action="" method="get">Cerca: <input id="id_q" name="q" type="text" name="textfield" style="width: 400px; height: 20px;"></form>{% csrf_token %}</div>
</div>

<div id="testosottocard">
	<!--
{% include "componenti/pagine/accatastamenti.html" %}
-->
	
{% block content %}
{% endblock %} 
</div>

</div>
<div id="rightside">
<p>&nbsp;</p>

{% include "componenti/login.html" %}
{% include "componenti/newsletter.html" %}
{% include "componenti/social.html" %}
<p>&nbsp;</p>
<p><a class="problem" href="{{ MYPATH }}/problematica">PARLACI</br>DELLA TUA</br>PROBLEMATICA</a></p>
<p></br></p>
<p><a class="richiest" href="{{ MYPATH }}/richiesta">RICHIESTA</br>INFORMAZIONI</a></p>
<!--
<p><img src="{{ STATIC_URL }}/img/rx.jpg" class="imgrx"></p>
-->
</div>


<div id="footero">
<div id="footeroleft"></div>
<div id="footerocenter"><img src="{{ STATIC_URL }}/img/loghifootera.jpg"></div>
</div>

<div id="footer">
<div id="footerleft"></div>
<div id="footercenter"></br>AS Servizi alle imprese s.r.l. -  C.F. e P.I: 02288730167  -  Via C. Maffei, 11 -  24128 BERGAMO  -  Tel. 035.238112 - Fax 035.224525 - <a href="mailto:info@asservizi.it">info@asservizi.it</a></div>
<div id="footerright">   </br>Designed by</br>grafica<B>PASSWORD</B></div>

</div>
</div>
</div>
</body>
</html>

sito/templates/contact.html
{% extends "base7.html" %}

{% block content %}

<div id="contenitorecard">
<p><H3>AS Servizi s.r.l.</h3></p>
<p>Via C. Maffei, 11 - 24128 BERGAMO</p>
<p>Tel. 035.238112 - Fax 035.224525</p>
<p><a href="mailto: info@asservizi.it">info@asservizi.it</a></p>
<p>&nbsp;</p>

<form action="/contact/" method="post">{% csrf_token %}
<p><label for="id_subject">Nome:</label></p>
<p><input id="id_subject" type="text" name="subject" class="contactform"/></p>
<p><label for="id_subject">Cognome:</label></p>
<p><input id="id_subject" type="text" name="subject" class="contactform" /></p>

<p><label for="id_subject">Indirizzo:</label></p>
<p><input id="id_address" type="text" name="address" class="contactform" /></p>

<p><label for="id_subject">Città:</label></p>
<p><input id="id_city" type="text" name="city" maxlength="250" class="contactform" /></p>

<p><label for="id_subject">Telefono:</label></p>
<p><input id="id_tel" type="text" name="tel" maxlength="100" class="contactform" /></p>

<p><label for="id_subject">Fax:</label></p>
<p><input id="id_fax" type="text" name="fax" maxlength="100" class="contactform"/></p>

<p><label for="id_sender">email:</label></p>
    <p><input type="email" name="sender" id="id_sender" class="contactform" /></p>

<p><label for="id_message">Messaggio:</label></p>
<p><textarea name="textarea" class="contactform" rows="6" cols="40" > </textarea></p>

<p><label for="id_cc_myself">Inviami una copia del messaggio:</label></p>
<P><input type="checkbox" name="cc_myself" id="id_cc_myself" /></p>
<input type="submit" value="Submit" />
</form>
</div>

{% endblock content %}

sito/templates/gallery.html
{% for galleria in galleria_list %}
{% load cropping %}
 <p><img src="{% cropped_thumbnail galleria "cropping" %}"></p>
 {% endfor %}

        

sito/templates/index.html
{% extends "base.html" %}

{% block content %}


<p class="titolo" style="color: #ae3624;"><br/>ASSERVIZI - Servizi alle Imprese</p>
<p></br></p>
<p>Via C. Maffei, 11 -  24128 BERGAMO</br>
Tel. 035.238112 - Fax 035.224525</br>
<a href="mailto:info@asservizi.it">info@asservizi.it</a></p>
<p></br></p>
<hr>
<p></br></p>
<p>Via Roma, 133/D-G - 24064 GRUMELLO DEL MONTE (BG)</br>
Tel. 035.833.843 - Fax 035.833.847</p>
<a href="mailto:info@asservizi.it">info@asservizi.it</a>
{% endblock content %}